{"uuid":"e4e603be-82aa-49e2-a8a0-809ada73a485","historyId":"caebf69f1a07b1cd5374ea5087ab69a0","fullName":"com.saucedemo.tests.BaseTest.setUp","labels":[{"name":"package","value":"com.saucedemo.tests.SauceDemoLoginExcelTest"},{"name":"testClass","value":"com.saucedemo.tests.SauceDemoLoginExcelTest"},{"name":"testMethod","value":"setUp"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"SauceDemoLoginExcelTest"},{"name":"subSuite","value":"com.saucedemo.tests.SauceDemoLoginExcelTest"},{"name":"host","value":"Balajis-MacBook-Pro.local"},{"name":"thread","value":"2538@Balajis-MacBook-Pro.local.TestNG-PoolService-1(45)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"setUp","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Balajis-MacBook-Pro.local', ip: '2405:201:e05f:d01f:dc6:6fe9:f6a8:869d%en0'","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Balajis-MacBook-Pro.local', ip: '2405:201:e05f:d01f:dc6:6fe9:f6a8:869d%en0'\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:562)\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:173)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:151)\n\tat com.saucedemo.driver.DriverFactory.getDriver(DriverFactory.java:63)\n\tat com.saucedemo.driver.DriverClass.initDriver(DriverClass.java:44)\n\tat com.saucedemo.tests.BaseTest.setUp(BaseTest.java:14)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:565)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:601)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)\n\tat org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)\n\tat java.base/java.lang.Thread.run(Thread.java:1447)\nCaused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException\nBuild info: version: '4.33.0', revision: '2c6aaad03a'\nSystem info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '15.5', java.version: '24.0.1'\nDriver info: driver.version: RemoteWebDriver\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:427)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)\n\tat org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:544)\n\t... 20 more\nCaused by: java.util.concurrent.TimeoutException\n\tat java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2990)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)\n\tat java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:328)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java)\n\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\n\tat java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:153)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.<init>(ScheduledThreadPoolExecutor.java:220)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:548)\n\tat java.base/java.util.concurrent.CompletableFuture$Delayer.delay(CompletableFuture.java:2939)\n\tat java.base/java.util.concurrent.CompletableFuture.orTimeout(CompletableFuture.java:2823)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.executeAsync(JdkHttpClient.java:408)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:413)\n\t... 27 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1753647555257,"stop":1753647555257}